query findByProximity(
  $latitude: Float!,
  $longitude: Float!,
  $googleMapsKey: String!
) {
  findByProximity(
    latitude: $latitude
    longitude: $longitude
  ) {
    _id
    name
    address
    place {
      photo(
        key: $googleMapsKey
      )
    }
    matrix(
      latitude: $latitude
      longitude: $longitude
    ) {
      distance
      duration
      mode
    }
  }
}
