query findByOne($id: String!, $latitude: Float!, $longitude: Float!) {
  findByProximity(
    _id: $id
    latitude: $latitude
    longitude: $longitude
    mode: driving
    units: metric
    time_type: departure_time
    time_value: "now"
  ) {
    _id
    name
    address
    geometry {
      coordinates
    }
    distance {
      text
      value
    }
    duration {
      text
      value
    }
  }
}
